export type {
  MvBlockPayload,
  MvFenceKind,
  MvMapPayload,
  MvMapRule,
  MvModelColumnDef,
  MvModelKvPayload,
  MvModelSqlPayload,
  MvModelSqlTable,
  MvModelStructPayload,
  MvModelCodespacePayload,
  MvModelCodespaceModule,
  MvCodespaceNamespaceNode,
  MvCodespaceClassifier,
  MvCodespaceClassifierBase,
  MvCodespaceClassifierKind,
  MvCodespaceBaseRelation,
  MvCodespaceClassMember,
  MvCodespaceClassMethod,
  MvCodespaceClassEnum,
  MvCodespaceProperty,
  MvCodespaceMethodKind,
  MvCodespaceFieldAccessor,
  MvCodespaceAccessorVisibility,
  MvCodespaceVariable,
  MvCodespaceFunction,
  MvCodespaceMacro,
  MvCodespaceAssociation,
  MvCodespaceAssociationEnd,
  MvCodespaceAssociationKind,
  MvModelInterfacePayload,
  MvModelInterfaceEndpoint,
  MvStructDataset,
  MvStructGroup,
  MvViewKind,
  MvViewPayload,
  ParseMdResult,
  ParsedFenceBlock,
  ParsedMermaidMirrorFence,
  ResolvedRef,
} from './types.js';

/** Core constants/functions: extension-agnostic public API */
export {
  MV_VIEW_KINDS,
  MV_VIEW_KIND_METADATA,
  MV_MERMAID_VIEW_KINDS,
  MV_MODEL_SQL_CANVAS_TITLE,
  MV_MODEL_CANVAS_TITLE,
  MV_MODEL_KV_CANVAS_TITLE,
  MV_MODEL_STRUCT_CANVAS_TITLE,
  MV_MODEL_CODESPACE_CANVAS_TITLE,
  MV_MODEL_INTERFACE_CANVAS_TITLE,
  MV_MAP_CANVAS_TITLE,
  MV_MODEL_REFS_SCHEME_DOC,
  MV_UML_VIEW_KINDS,
  MV_UML_KIND_DIAGRAM_TYPE,
  getMermaidViewKinds,
  getMermaidNonUmlViewKinds,
  MV_MERMAID_UML_INSERT_KINDS,
  isMermaidViewKind,
  isUmlViewKind,
} from './types.js';

/** Compatibility aliases: kept for older callers, prefer core API names above */
export { MV_PLANTUML_VIEW_KINDS, isPlantUmlViewKind } from './types.js';

export { parseMarkdownBlocks, replaceBlockInnerById, getBlockFenceSlice, findMvModelSqlTable } from './parse/blocks.js';
export { parseRefUri, normalizeRelPath, resolveRefPath, detectRefCycle } from './refs/resolve.js';

export type {
  ClassDef,
  ClassDiagramState,
  ClassLink,
  ClassPositions,
  ClassDiagramEdgeVisibility,
  ParsedClassLayout,
} from './mermaid/classDiagramModel.js';
export {
  slug,
  stripMermaidMemberModifiers,
  isClassMemberMethodLine,
  emptyDiagram,
  parseLayoutComment,
  extractFirstMermaidBlock,
  parseClassDiagramBody,
  serializeClassDiagramBody,
  mergePositions,
  buildClassDiagramMarkdown,
  parseOrDefault,
  classDiagramHeaderHeight,
  estimateClassSize,
  diagramBounds,
  extractClassDiagramSourceFromPayload,
  parseViewPayloadClassDiagram,
  buildClassDiagramViewPayload,
} from './mermaid/classDiagramModel.js';
